In [1]:
import numpy as np

In [2]:
def convolve2d(image, kernel):
    # Dimensions of the image and kernel
    image_height, image_width = image.shape
    kernel_height, kernel_width = kernel.shape

    # Calculate the dimensions of the output image
    output_height = image_height - kernel_height + 1
    output_width = image_width - kernel_width + 1

    # Initialize the output image with zeros
    output = np.zeros((output_height, output_width))

    # Perform convolution
    for i in range(output_height):
        for j in range(output_width):
            # Extract the current region of interest from the image
            current_region = image[i:i+kernel_height, j:j+kernel_width]
            # Perform element-wise multiplication and sum the result
            output[i, j] = np.sum(current_region * kernel)

    return output


In [3]:
# Define a new original image with an edge
original_image_with_edge = np.array([
    [10, 10, 10, 10, 10, 10],
    [10, 10, 10, 10, 10, 10],
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0]
])

# Define a 3x3 filter (kernel)
kernel = np.array([
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
])

# Apply the convolution operation to the image with an edge
output_image_with_edge = convolve2d(original_image_with_edge, kernel)

print("Output Image with Edge:")
print(output_image_with_edge)

Output Image with Edge:
[[  0.   0. -10. -10.]
 [  0. -10.  20.  10.]
 [  0. -10.  10.   0.]
 [  0. -10.  10.   0.]]
